/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppQuotesRouteImport } from './routes/_app.quotes'
import { Route as AppMessagesRouteImport } from './routes/_app.messages'
import { Route as AppLagerRouteImport } from './routes/_app.lager'
import { Route as AppKoretojerRouteImport } from './routes/_app.koretojer'
import { Route as AppJobsRouteImport } from './routes/_app.jobs'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppCrewRouteImport } from './routes/_app.crew'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppLeadsIndexRouteImport } from './routes/_app.leads.index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app.customers.index'
import { Route as AppBriefIndexRouteImport } from './routes/_app.brief.index'
import { Route as AppLeadsLeadIdRouteImport } from './routes/_app.leads.$leadId'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/_app.customers.$customerId'
import { Route as AppBriefBriefIdRouteImport } from './routes/_app.brief.$briefId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesRoute = AppQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppLagerRoute = AppLagerRouteImport.update({
  id: '/lager',
  path: '/lager',
  getParentRoute: () => AppRoute,
} as any)
const AppKoretojerRoute = AppKoretojerRouteImport.update({
  id: '/koretojer',
  path: '/koretojer',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppCrewRoute = AppCrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppBriefIndexRoute = AppBriefIndexRouteImport.update({
  id: '/brief/',
  path: '/brief/',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsLeadIdRoute = AppLeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => AppRoute,
} as any)
const AppBriefBriefIdRoute = AppBriefBriefIdRouteImport.update({
  id: '/brief/$briefId',
  path: '/brief/$briefId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/calendar': typeof AppCalendarRoute
  '/crew': typeof AppCrewRoute
  '/inventory': typeof AppInventoryRoute
  '/jobs': typeof AppJobsRoute
  '/koretojer': typeof AppKoretojerRoute
  '/lager': typeof AppLagerRoute
  '/messages': typeof AppMessagesRoute
  '/quotes': typeof AppQuotesRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/brief/$briefId': typeof AppBriefBriefIdRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/brief/': typeof AppBriefIndexRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/leads/': typeof AppLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/calendar': typeof AppCalendarRoute
  '/crew': typeof AppCrewRoute
  '/inventory': typeof AppInventoryRoute
  '/jobs': typeof AppJobsRoute
  '/koretojer': typeof AppKoretojerRoute
  '/lager': typeof AppLagerRoute
  '/messages': typeof AppMessagesRoute
  '/quotes': typeof AppQuotesRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/': typeof AppIndexRoute
  '/brief/$briefId': typeof AppBriefBriefIdRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/brief': typeof AppBriefIndexRoute
  '/customers': typeof AppCustomersIndexRoute
  '/leads': typeof AppLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/crew': typeof AppCrewRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/koretojer': typeof AppKoretojerRoute
  '/_app/lager': typeof AppLagerRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/quotes': typeof AppQuotesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/': typeof AppIndexRoute
  '/_app/brief/$briefId': typeof AppBriefBriefIdRoute
  '/_app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/_app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/_app/brief/': typeof AppBriefIndexRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/leads/': typeof AppLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/crew'
    | '/inventory'
    | '/jobs'
    | '/koretojer'
    | '/lager'
    | '/messages'
    | '/quotes'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/brief/$briefId'
    | '/customers/$customerId'
    | '/leads/$leadId'
    | '/brief/'
    | '/customers/'
    | '/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/calendar'
    | '/crew'
    | '/inventory'
    | '/jobs'
    | '/koretojer'
    | '/lager'
    | '/messages'
    | '/quotes'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/'
    | '/brief/$briefId'
    | '/customers/$customerId'
    | '/leads/$leadId'
    | '/brief'
    | '/customers'
    | '/leads'
  id:
    | '__root__'
    | '/_app'
    | '/_app/calendar'
    | '/_app/crew'
    | '/_app/inventory'
    | '/_app/jobs'
    | '/_app/koretojer'
    | '/_app/lager'
    | '/_app/messages'
    | '/_app/quotes'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/tasks'
    | '/_app/'
    | '/_app/brief/$briefId'
    | '/_app/customers/$customerId'
    | '/_app/leads/$leadId'
    | '/_app/brief/'
    | '/_app/customers/'
    | '/_app/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes': {
      id: '/_app/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof AppQuotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lager': {
      id: '/_app/lager'
      path: '/lager'
      fullPath: '/lager'
      preLoaderRoute: typeof AppLagerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/koretojer': {
      id: '/_app/koretojer'
      path: '/koretojer'
      fullPath: '/koretojer'
      preLoaderRoute: typeof AppKoretojerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crew': {
      id: '/_app/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof AppCrewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/': {
      id: '/_app/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AppLeadsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brief/': {
      id: '/_app/brief/'
      path: '/brief'
      fullPath: '/brief/'
      preLoaderRoute: typeof AppBriefIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/$leadId': {
      id: '/_app/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AppLeadsLeadIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$customerId': {
      id: '/_app/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brief/$briefId': {
      id: '/_app/brief/$briefId'
      path: '/brief/$briefId'
      fullPath: '/brief/$briefId'
      preLoaderRoute: typeof AppBriefBriefIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppCrewRoute: typeof AppCrewRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppJobsRoute: typeof AppJobsRoute
  AppKoretojerRoute: typeof AppKoretojerRoute
  AppLagerRoute: typeof AppLagerRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppQuotesRoute: typeof AppQuotesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBriefBriefIdRoute: typeof AppBriefBriefIdRoute
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppLeadsLeadIdRoute: typeof AppLeadsLeadIdRoute
  AppBriefIndexRoute: typeof AppBriefIndexRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppLeadsIndexRoute: typeof AppLeadsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppCrewRoute: AppCrewRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppJobsRoute: AppJobsRoute,
  AppKoretojerRoute: AppKoretojerRoute,
  AppLagerRoute: AppLagerRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppQuotesRoute: AppQuotesRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
  AppBriefBriefIdRoute: AppBriefBriefIdRoute,
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppLeadsLeadIdRoute: AppLeadsLeadIdRoute,
  AppBriefIndexRoute: AppBriefIndexRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppLeadsIndexRoute: AppLeadsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
